#!/bin/sh
set -e

#DEBHELPER#

PKG=pr2-installer

case "$1" in
  configure)

        mkdir -p /usr/lib/robot-install/keydir
        gpg -q --homedir /usr/lib/robot-install/keydir --import /usr/lib/robot-install/pr2-packages.key || :
        gpg -q --homedir /usr/lib/robot-install/keydir --import /usr/lib/robot-install/basestationpackages.gpg || :

        ln -s /var/www/pr2-packages /var/www/html/pr2-packages
        rm /var/www/html/index.html
        ln -s /var/www/index.html /var/www/html/index.html
        ln -s /var/www/robot_xenial64.preseed /var/www/html/robot_xenial64.preseed

    ;;
  
  *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
